
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapp.context-testing.pivotal.io
  resources:
  - guestbooks
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - webapp.context-testing.pivotal.io
  resources:
  - guestbooks/status
  verbs:
  - get
  - update
  - patch
- apiGroups: 
  - extensions
  resources: 
  - podsecuritypolicies
  resourceNames: 
  - $(MANAGER_PSP)
  verbs:
  - use